### ISSUE TITLE
Addition 1: Highlight Selected Answer

### ISSUE THREAD

**Issue by PatrickFrankAIU** [PatrickFrankAIU/QuizApp#1]
The goal of this step is to make the program highlight the selected answer after it is assessed, so that the student/user can see which answer they selected and confirm that it was the one they intended. 

**Goals:**
- Highlight the selected answer with a different style.
- Display a message indicating the selected answer and whether it was correct.
(No HTML changes are needed for this exercise.) 

**Task 1: CSS Changes**
- [ ] Add a new style for the selected answer and a message to display the result. (Example shown below. Note that the result-message ID tag is used by the JavaScript shown in Task 2 below.) 

_Suggested Code (CSS):_ 
```
.selected {
    background-color: yellow;
}

#result-message {
    margin-top: 20px;
    font-size: 18px;
}
```

**Task 2: JavaScript Changes** 
- [ ] Create "resultMessageElement" to display the selected answer and whether it was correct or incorrect
- [ ] Update the "showQuestion" function to clear the result message when a new question is displayed
- [ ] Modified the "selectAnswer" function to display the result message and highlight the selected answer
- [ ] Ensure that the "resultMessageElement" you created above is shown or hidden as appropriate

_Suggested Code (JS):_ 
1. Add new result message element. These lines should be placed immediately after the existing variable declarations, which are just below the array object near the top of the file.  
```
const resultMessageElement = document.createElement('div');
resultMessageElement.id = 'result-message';
document.querySelector('.container').appendChild(resultMessageElement);
```
2. Modify the startQuiz function to hide the result message at the start: 
```
function startQuiz() {
    currentQuestionIndex = 0;
    nextButton.classList.add('hide');
    resultMessageElement.classList.add('hide'); // this is the new line (rest is the same) 
    showQuestion(questions[currentQuestionIndex]);
}
```
3. Modify the showQuestion function to clear and hide the result message when a new question is displayed: 
```
function showQuestion(question) {
    questionElement.innerText = question.question;
    answerButtonsElement.innerHTML = '';
    resultMessageElement.innerText = ''; // new line
    resultMessageElement.classList.add('hide'); // new line
    question.answers.forEach(answer => {
        const button = document.createElement('button');
        button.innerText = answer.text;
        button.classList.add('btn');
        button.addEventListener('click', () => selectAnswer(button, answer)); // changed line!
        answerButtonsElement.appendChild(button);
    });
}
```
4. Modify the selectAnswer function to display the result message and highlight the selected answer: 
```
function selectAnswer(button, answer) { // changed line
    const buttons = answerButtonsElement.children;
    Array.from(buttons).forEach(btn => {
        btn.classList.add('incorrect'); // changed line
        btn.disabled = true; // new line
    });
    if (answer.correct) { // changed line
        button.classList.remove('incorrect'); // new line
        button.classList.add('correct');
        resultMessageElement.textContent = `You selected: "${answer.text}". That's correct!`; // new line
    } else {
        button.classList.add('incorrect');
        resultMessageElement.innerText = `You selected: "${answer.text}". That's incorrect!`; // new line
    }
    /* Array.from(buttons).forEach(btn => {
        btn.disabled = true;
    }); */ // loop removed
    resultMessageElement.classList.remove('hide'); // new line
    nextButton.classList.remove('hide');
}
```
5. Modify the showResults function to hide the result message upon quiz completion: 
```
function showResults() {
    questionElement.innerText = 'Quiz Completed!';
    answerButtonsElement.innerHTML = '';
    nextButton.classList.add('hide');
    resultMessageElement.classList.add('hide'); // new line
}
```

Test your code and discuss the results with the instructor.
